// Embedded by build.mjs. No imports, network dependencies, or solver impersonation.
(() => {
  'use strict';
  const originalHtml='<!doctype html>\n'+document.documentElement.outerHTML;
  const M=window.CourseMath,D=window.CourseData;
  const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const f=(n,d=1)=>Number(n).toLocaleString('en',{minimumFractionDigits:d,maximumFractionDigits:d});
  const download=(name,body,type='text/plain')=>{const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  function read(key,fallback) {try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
  function write(key,value) {try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
  const appRoot=location.protocol==='file:'?'https://easy-cfd.mthracelab.com/':new URL('../',location.href).href;
  $$('[data-app-back]').forEach(a=>a.href=appRoot);
  $$('[data-app-lab]').forEach(a=>a.href=appRoot+'?courseLab=teaching-car');
  $$('[data-app-doc]').forEach(a=>a.href=appRoot+'VALIDATION.md');
  $('#menu-toggle').addEventListener('click',()=>{const open=$('.sidebar').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));});
  $$('.sidebar a').forEach(a=>a.addEventListener('click',()=>{$('.sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}));
  const lessons=$$('.lesson'),nav=$$('[data-lesson-link]'),completed=new Set(read('easycfd.course.completed',[]));
  function progress(){const n=lessons.filter(l=>completed.has(l.id)).length;$('#course-progress').value=n;$('#progress-label').textContent=`${n} of 24 lessons completed`;nav.forEach(a=>a.classList.toggle('completed',completed.has(a.dataset.lessonLink)));}
  lessons.forEach(l=>{const label=document.createElement('label');label.className='complete-lesson no-print';label.innerHTML=`<input type="checkbox" ${completed.has(l.id)?'checked':''}>Mark lesson ${Number(l.id.slice(-2))} complete`;l.append(label);$('input',label).addEventListener('change',e=>{e.target.checked?completed.add(l.id):completed.delete(l.id);write('easycfd.course.completed',[...completed]);progress();});});progress();
  const remembered=read('easycfd.course.last','lesson-01');$('#resume').addEventListener('click',()=>{location.hash=document.getElementById(remembered)?remembered:'lesson-01';});
  let scheduled=false;
  function track(){scheduled=false;let current=lessons[0];for(const l of lessons)if(l.getBoundingClientRect().top<=innerHeight*.35)current=l;nav.forEach(a=>a.classList.toggle('active',a.dataset.lessonLink===current.id));if(current.getBoundingClientRect().top<innerHeight)write('easycfd.course.last',current.id);}
  addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(track);}}, {passive:true});
  $('#course-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();let matches=0;nav.forEach(a=>{const lesson=document.getElementById(a.dataset.lessonLink),show=!q||lesson.textContent.toLowerCase().includes(q);a.hidden=!show;matches+=show?1:0;});$('#search-status').textContent=q?`${matches} matching lessons. Full text remains available.`:'';});
  const notes=$('#course-notes');notes.value=read('easycfd.course.notes','');
  notes.addEventListener('input',()=>{$('#notes-status').textContent=write('easycfd.course.notes',notes.value)?'Notes saved in this browser.':'Browser storage is unavailable. Export notes to keep them.';});
  $('#export-notes').addEventListener('click',()=>download('easycfd-course-notes.txt',notes.value));
  $('#download-html').addEventListener('click',()=>download('easycfd-car-aerodynamics.html',originalHtml,'text/html'));
  $$('[data-download-models]').forEach(b=>b.addEventListener('click',()=>download('easycfd-teaching-car.zip',Uint8Array.from(atob(D.modelZip),c=>c.charCodeAt(0)),'application/zip')));
  $$('[data-download-evidence]').forEach(b=>b.addEventListener('click',()=>download('easycfd-course-runs.json',JSON.stringify(D.evidence,null,2),'application/json')));
  $$('[data-download-workbook]').forEach(b=>b.addEventListener('click',()=>download('easycfd-aero-workbook.csv','lab,run,geometry,enabled_body,enabled_wing,other_groups,prediction,speed_kmh,yaw_deg,front_height_m,rear_height_m,density_kg_m3,reference_area_m2,engine,resolution,cells,grid_id,averaging_window,cd,cl,drag_N,downforce_N,front_aero_N,rear_aero_N,pitch_Nm,moment_origin,settled,cd_band,cl_band,warnings,observation,interpretation,next_test\n'+Array.from({length:12},(_,i)=>`${i+1},${','.repeat(31)}\n`).join(''),'text/csv')));
  function metric(name,value){return `<div class="metric"><strong>${value}</strong><span>${name}</span></div>`;}
  function slider(root,key,label,min,max,step,value,unit=''){const id=`${root.dataset.widget}-${key}`;return `<div class="control"><label for="${id}">${label}<output for="${id}" data-value="${key}"></output></label><input id="${id}" name="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-unit="${unit}" aria-label="${label}"></div>`;}
  function mount(root,controls,render){root.insertAdjacentHTML('beforeend',`<div class="controls">${controls}</div><div class="widget-result" aria-live="polite" aria-atomic="true"></div>`);const update=()=>{const values={};$$('input',root).forEach(i=>{values[i.name]=Number(i.value);$(`[data-value="${i.name}"]`,root).textContent=`${i.value}${i.dataset.unit}`;});$('.widget-result',root).innerHTML=render(values);};root.addEventListener('input',update);update();}
  function plot({points,label,xlabel,ylabel,color='#17776a',width=760,height=280,mean=null}){
    if(!points.length)return '<p>No history samples were saved.</p>';
    const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);
    const margin=Math.max((ymax-ymin)*.12,.005);ymin-=margin;ymax+=margin;if(xmax===xmin)xmax=xmin+1;
    const X=x=>65+(x-xmin)/(xmax-xmin)*(width-95),Y=y=>height-53-(y-ymin)/(ymax-ymin)*(height-115);
    let body=`<title>${escape(label)}</title><text x="20" y="28" font-size="18" fill="#193c46">${escape(label)}</text>`;
    for(let i=0;i<=4;i++){const yy=ymin+(ymax-ymin)*i/4;body+=`<line x1="65" y1="${Y(yy)}" x2="${width-30}" y2="${Y(yy)}" stroke="#e0e8e1"/><text x="7" y="${Y(yy)+5}" font-size="13" fill="#53676b">${f(yy,3)}</text>`;}
    body+=`<line x1="65" y1="${height-53}" x2="${width-30}" y2="${height-53}" stroke="#53676b"/>`;
    body+=`<path d="${points.map(([x,y],i)=>`${i?'L':'M'}${X(x).toFixed(2)} ${Y(y).toFixed(2)}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2.5"/>`;
    if(mean!==null&&mean>=ymin&&mean<=ymax)body+=`<line x1="65" y1="${Y(mean)}" x2="${width-30}" y2="${Y(mean)}" stroke="#bc6034" stroke-dasharray="5 5"/>`;
    body+=`<text x="65" y="${height-31}" font-size="13">${f(xmin,2)}</text><text x="${width-75}" y="${height-31}" font-size="13">${f(xmax,2)}</text><text x="${width/2-80}" y="${height-10}" font-size="15">${escape(xlabel)}</text><text x="65" y="53" font-size="14">${escape(ylabel)}</text>`;
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escape(label)}" style="font-family:Arial,sans-serif">${body}</svg>`;
  }
  const widgets={
    forces(root){mount(root,slider(root,'speed','Road speed (still air)',40,260,5,100,' km/h')+slider(root,'cd','Drag coefficient Cd',.1,1,.01,.32)+slider(root,'cl','Signed lift coefficient Cl',-1.5,1,.05,-.4)+slider(root,'area','Car reference area',1,3,.1,2.2,' m²')+slider(root,'density','Air density',.9,1.4,.025,1.225,' kg/m³'),v=>{const r=M.forceModel(v);return `<div class="metrics">${metric('Dynamic pressure',f(r.q)+' Pa')}${metric('Drag',f(r.drag)+' N')}${metric('Downforce (negative = uplift)',f(r.downforce)+' N')}${metric('Still-air aero power',f(r.power,2)+' kW')}${metric('Car-length Reynolds number',f(r.re/1e6,2)+' million')}${metric('Mach (a = 343 m/s)',f(r.mach,3))}</div>`+plot({points:Array.from({length:45},(_,i)=>[i*6,M.forceModel({...v,speed:i*6}).drag]),label:'Constant-Cd drag curve',xlabel:'Speed [km/h]',ylabel:'Drag [N]'})});},
    wing(root){mount(root,slider(root,'angle','Downforce incidence',-2,18,.5,6,'°')+slider(root,'span','Span',1,2.2,.05,1.7,' m')+slider(root,'chord','Chord',.15,.6,.01,.32,' m')+slider(root,'speed','Freestream speed',60,240,5,100,' km/h')+slider(root,'localRatio','Local / freestream speed',.5,1.2,.05,1),v=>{const r=M.wingModel(v);return `<div class="metrics">${metric('Wing planform area',f(r.area,3)+' m²')}${metric('Aspect ratio',f(r.ar,2))}${metric('Wing CN (planform area)',f(r.cn,3))}${metric('Teaching-model downforce',f(r.downforce)+' N')}${metric('Profile + induced drag',f(r.drag)+' N')}${metric('Induced Cd only',f(r.cdi,3))}</div><p class="widget-message ${r.extrapolated?'warning':''}">${r.extrapolated?'High-incidence linear extrapolation. This model cannot detect stall or establish a usable load.':'Attached-flow estimate only. The installed NACA geometry may have a different polar and inflow.'}</p>`+plot({points:Array.from({length:41},(_,i)=>{const a=-2+i*.5,w=M.wingModel({...v,angle:a});return[w.drag,w.downforce]}),label:'Assumed attached-wing force tradeoff',xlabel:'Wing drag [N]',ylabel:'Wing downforce [N]'})});},
    diffuser(root){mount(root,slider(root,'height','Throat height',.05,.25,.005,.14,' m')+slider(root,'length','Ramp length',.3,1.3,.05,.95,' m')+slider(root,'angle','Ramp angle',0,20,.5,7,'°'),v=>{const r=M.diffuserModel(v),y=235-(r.exit/v.height-1)*33;return `<div class="metrics">${metric('Exit height',f(r.exit*1000,1)+' mm')}${metric('Geometric area ratio',f(r.ratio,2))}${metric('Ideal exit speed',f(r.exitSpeed,2)+' m/s')}${metric('Ideal recovery fraction',f(100*r.recoveryFraction,1)+'%')}${metric('Ideal pressure recovery',f(r.recovery,1)+' Pa')}${metric('Predicted car downforce','Not modeled')}</div><svg viewBox="0 0 760 280" role="img" aria-label="Adjustable diffuser geometry schematic"><title>Diffuser geometry, vertical expansion exaggerated</title><line x1="45" y1="250" x2="715" y2="250" stroke="#193c46" stroke-width="4"/><path d="M60 215 L330 215 L690 ${Math.max(45,y)}" fill="none" stroke="#17776a" stroke-width="10"/><text x="60" y="190" fill="#193c46" font-size="19">Floor / throat</text><text x="425" y="45" font-size="19">Ramp ${f(v.angle,1)}° (schematic)</text><text x="60" y="275" font-size="16">Road · geometric expansion only; no solved flow</text></svg>`;});},
    balance(root){mount(root,slider(root,'wheelbase','Wheelbase',2,3.2,.05,2.6,' m')+slider(root,'frontLoad','Splitter downward load',0,600,10,150,' N')+slider(root,'frontPosition','Splitter position aft of front axle',-.8,.3,.05,-.4,' m')+slider(root,'rearLoad','Wing downward load',0,1200,20,500,' N')+slider(root,'rearPosition','Wing position aft of front axle',1.5,3.6,.05,3,' m'),v=>{const r=M.balanceModel(v);return `<div class="metrics">${metric('Total positive downforce',f(r.total)+' N')}${metric('Front equivalent aero load',f(r.front)+' N')}${metric('Rear equivalent aero load',f(r.rear)+' N')}${metric('Rear-loading moment',f(r.moment)+' N·m')}${metric('Front fraction',r.frontFraction===null?'Undefined':f(100*r.frontFraction)+'%')}${metric('Force closure',f(r.front+r.rear-r.total,3)+' N')}</div><p class="widget-message ${r.front<0?'warning':''}">${r.front<0?'Front axle is aerodynamically unloaded in this point-load model.':'Equivalent aero loads are statics increments, not a tyre-grip or handling prediction.'}</p>`;});},
    gci(root){mount(root,slider(root,'fine','Fine-grid metric',.25,.4,.0005,.3)+slider(root,'medium','Medium-grid metric',.25,.4,.0005,.306)+slider(root,'coarse','Coarse-grid metric',.25,.4,.0005,.3195)+slider(root,'ratio','Constant spacing ratio r',1.1,2,.05,1.5),v=>{const r=M.gciModel(v);if(!r.valid)return `<p class="widget-message warning">${r.reason}</p>`;return `<div class="metrics">${metric('Observed order p',f(r.order,3))}${metric('Extrapolated metric',f(r.extrapolated,5))}${metric('Fine-grid GCI',f(r.gci*100,2)+'%')}</div><p class="widget-message">Requires comparable, converged grids in an asymptotic regime. A ${f(r.gci*100,2)}% GCI is not a physical-accuracy claim.</p>`;});},
    yaw(root){mount(root,slider(root,'roadSpeed','Road speed',40,240,5,100,' km/h')+slider(root,'headwind','Headwind (negative = tailwind)',-10,20,1,0,' m/s')+slider(root,'crosswind','Lateral crosswind',-15,15,.5,5,' m/s'),v=>{const r=M.yawModel(v);return `<div class="metrics">${metric('Road motion / rolling speed',f(r.road,2)+' m/s')}${metric('Relative airspeed',f(r.airspeed,2)+' m/s')}${metric('Yaw magnitude and sign',f(r.yaw,2)+'°')}${metric('Relative-air dynamic pressure',f(r.q,1)+' Pa')}</div><p class="widget-message">The moving road has no lateral wind component. Wheel rotation follows the ${f(r.road,2)} m/s road-relative motion.</p>`;});},
    pareto(root){const candidates=[{name:'Baseline',drag:0,load:0,front:50},{name:'Small front package',drag:25,load:180,front:64},{name:'Balanced package',drag:70,load:520,front:47},{name:'Rear-heavy wing',drag:100,load:760,front:25},{name:'Large balanced package',drag:150,load:850,front:44},{name:'Inefficient package',drag:135,load:500,front:47}];mount(root,slider(root,'maxPower','Added power ceiling at 200 km/h',0,10,.25,6,' kW')+slider(root,'minFront','Minimum front aero fraction',10,70,1,40,'%'),v=>{const feasible=candidates.filter(c=>c.drag*(200/3.6)/1000<=v.maxPower&&c.front>=v.minFront),nondominated=new Set(M.frontier(feasible));let html='<div class="table-wrap"><table><caption>Synthetic candidates evaluated at 200 km/h</caption><thead><tr><th>Candidate</th><th>ΔD [N]</th><th>ΔN [N]</th><th>Front [%]</th><th>Status</th></tr></thead><tbody>';for(const c of candidates)html+=`<tr><th>${c.name}</th><td>${c.drag}</td><td>${c.load}</td><td>${c.front}</td><td>${!feasible.includes(c)?'Outside constraints':nondominated.has(c)?'Feasible frontier':'Dominated'}</td></tr>`;return html+'</tbody></table></div><p class="widget-message">Changing a constraint changes the candidate set. A frontier still needs operating-envelope and uncertainty checks.</p>';});},
    evidence(root){const rows=D.evidence.cases.filter(c=>c.result);root.insertAdjacentHTML('beforeend','<label for="evidence-case" class="fine-print">Captured run</label> <select id="evidence-case">'+rows.map(c=>`<option value="${escape(c.id)}">${escape(c.id)}</option>`).join('')+'</select><div class="evidence-result" aria-live="polite"></div>');const update=()=>{const c=rows.find(c=>c.id===$('#evidence-case').value),r=c.result;$('.evidence-result',root).innerHTML=`<div class="chart-pair">${plot({points:r.history.map(h=>[h.time,h.cd]),label:c.id+' / actual Cd history',xlabel:'Solver pseudo-time [s]',ylabel:'Cd',width:400,height:285,mean:r.cd})}${plot({points:r.history.map(h=>[h.time,h.cl]),label:c.id+' / actual Cl history',xlabel:'Solver pseudo-time [s]',ylabel:'Signed Cl',color:'#287fc0',width:400,height:285,mean:r.cl})}</div><p class="widget-message ${r.settled?'':'warning'}">${r.settled?'Temporal settling test passed; physical accuracy remains unqualified.':'Temporal settling test did not pass. The final-window mean is provisional.'} Dashed line: saved averaged coefficient. ${escape((r.warnings??[]).join(' '))}</p>`;};$('#evidence-case').addEventListener('change',update);update();}
  };
  for(const root of $$('[data-widget]'))widgets[root.dataset.widget](root);
  const e=D.evidence,base=e.cases.find(c=>c.id==='baseline').result;
  $('#evidence-meta').innerHTML=`<p class="fine-print">Captured ${escape(e.capturedAt.slice(0,10))} · source commit ${escape(e.commit.slice(0,12))} · ${escape(base.adapter)} · ${f(e.settings.custom_cells,0)} cells/length, ${f(e.settings.custom_passes,0)} requested passes · 100 km/h · Aref 2.2 m². Source: web/course/evidence/runs.json.</p>`;
  $('#evidence-table').innerHTML='<div class="table-wrap"><table><caption>Actual exploratory course-run output · signed coefficients, saved means</caption><thead><tr><th>Case</th><th>Cd</th><th>Cl</th><th>Δ downforce [N]</th><th>Cells</th><th>Settled?</th><th>Runtime [s]</th></tr></thead><tbody>'+e.cases.map(c=>c.result?`<tr><th>${escape(c.id)}</th><td>${f(c.result.cd,4)}<br><span class="fine-print">±${f(c.result.cdBand??0,4)}</span></td><td>${f(c.result.cl,4)}<br><span class="fine-print">±${f(c.result.clBand??0,4)}</span></td><td>${f(c.result.downforce-base.downforce,1)}</td><td>${f(c.result.cells,0)}</td><td class="${c.result.settled?'pass':'warning'}">${c.result.settled?'Yes':'No'}</td><td>${f(c.result.wallSeconds,0)}</td></tr>`:`<tr><th>${escape(c.id)}</th><td colspan="6">Failed: ${escape(c.error)}</td></tr>`).join('')+'</tbody></table></div><p class="fine-print">Bands are half-ranges of sub-window means. “Settled” describes temporal behaviour only. Wall runtimes reflect the capture machine and its GPU load; they are not a controlled performance benchmark. Whole-car wing results here do not establish a valid real-wing ranking.</p>';
  $('#feature-issues').innerHTML='<ul>'+D.issues.map(i=>`<li><a href="${escape(i.url)}">#${i.number} · ${escape(i.title)}</a>${i.existing?' (existing issue)':''}</li>`).join('')+'</ul>';
  let openBefore=null;
  function preparePrint(){if(openBefore!==null)return;openBefore=$$('details').filter(d=>!d.open);$$('details').forEach(d=>d.open=true);document.documentElement.classList.add('printing');}
  function restorePrint(){if(openBefore===null)return;openBefore.forEach(d=>d.open=false);openBefore=null;document.documentElement.classList.remove('printing');}
  window.course={preparePrint,restorePrint,ready:true};
  addEventListener('beforeprint',preparePrint);addEventListener('afterprint',restorePrint);
  $('#print-course').addEventListener('click',()=>window.print());
  // Download the pristine delivered HTML, including embedded data, rather than current note values.
  // Capturing before DOM updates avoids leaking browser-local notes/progress.
})();
