// Capture a driving preview using an existing folder of body/wheel STL files.
// Start the dev server, then: node demo/record-driving.mjs /path/to/car /path/to/output
import { chromium } from "@playwright/test";
import { mkdirSync, readdirSync } from "node:fs";
import { basename, resolve } from "node:path";
const input = resolve(process.argv[2] ?? "../.easycfd/imports/mx5-nc");
const output = resolve(process.argv[3] ?? "../.easycfd/previews/driving");
const forward = process.argv[4] ?? "-X";
const name = process.argv[5] ?? basename(input);
mkdirSync(output, { recursive: true });
const files = readdirSync(input).filter(name => /\.stl$/i.test(name)).map(name => resolve(input, name));
if (!files.length) throw new Error("The model folder needs STL files, with wheels named wheel*.stl.");
const browser = await chromium.launch({ headless: true, args: ["--enable-unsafe-webgpu", "--use-angle=metal", "--enable-gpu", "--ignore-gpu-blocklist"] });
const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, colorScheme: "dark", recordVideo: { dir: output, size: { width: 1600, height: 1000 } } });
const started = Date.now();
const page = await context.newPage();
const errors = [];
page.on("pageerror", e => errors.push(e.message));
page.on("console", m => { if (m.type() === "error") errors.push(m.text()); });
await page.goto(process.env.EASYCFD_PREVIEW_URL ?? "http://127.0.0.1:5173/");
await page.locator('input[type="file"]').first().setInputFiles(files);
await page.getByRole("region", { name: "Driving preview" }).waitFor({ timeout: 60000 });
await page.waitForFunction(() => {
  const s = window.__easycfd?.app.get();
  return s && !s.busy && s.parts.filter(p => p.role === "wheel").length === 4;
}, null, { timeout: 60000 });
await page.getByRole("combobox", { name: "Nose direction in the file" }).selectOption(forward);
await page.waitForFunction(() => !window.__easycfd.app.get().busy);
await page.getByRole("textbox", { name: "Design name" }).fill(name);
await page.getByRole("textbox", { name: "Design name" }).press("Enter");
await page.getByText("I checked size, orientation, wheels and clearance.").click();
await page.getByRole("button", { name: "Continue to conditions" }).click();
await page.getByRole("slider", { name: "Yaw (crosswind)" }).fill("8");
await page.getByRole("radio", { name: "½×", exact: true }).click();
await page.locator(".panel").evaluate(el => { el.scrollTop = 0; });
await page.waitForTimeout(1200);
await page.screenshot({ path: resolve(output, "driving-preview.png") });
await page.getByRole("button", { name: "Expand view" }).click();
await page.waitForTimeout(1200);
const clipStart = (Date.now() - started) / 1000;
await page.screenshot({ path: resolve(output, "driving-expanded.png") });
await page.waitForTimeout(7500);
await page.getByRole("button", { name: "Pause animation" }).click();
await page.waitForTimeout(700);
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole("button", { name: "Play animation" }).click();
await page.waitForTimeout(1000);
await page.screenshot({ path: resolve(output, "driving-phone.png") });
console.log(JSON.stringify({ errors, clipStart, screenshots: ["driving-preview.png", "driving-expanded.png", "driving-phone.png"], model: input }));
const video = page.video();
await context.close();
console.log(JSON.stringify({ video: await video.path() }));
await browser.close();
if (errors.length) process.exitCode = 1;
