import { chromium, expect } from '../frontend/node_modules/@playwright/test/index.mjs';
import { readFile, writeFile } from 'node:fs/promises';
const out=new URL('../docs/transform-demo/',import.meta.url).pathname;
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:out,size:{width:1440,height:1000}}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8012');
await page.getByRole('button',{name:/Designs/}).first().click();
await page.getByRole('button',{name:/BMW Z4 · live dimensions demo/}).click();
await page.getByRole('button',{name:'Rotate & scale',exact:true}).click();
const dialog=page.getByRole('dialog',{name:'Rotate and scale'});
const length=dialog.getByLabel('Length · X',{exact:true});await expect(length).toBeEnabled();
const pause=ms=>page.waitForTimeout(ms);
async function caption(text){await dialog.evaluate((el,text)=>{let d=el.querySelector('#demo-caption');if(!d){d=document.createElement('div');d.id='demo-caption';el.appendChild(d);}d.style.cssText='position:absolute;left:365px;right:25px;bottom:135px;background:#112a32ed;color:white;padding:15px;border-radius:8px;font:16px/1.5 system-ui;z-index:100;pointer-events:none';d.textContent=text;},text);}
await caption('Rotate and scale the current geometry, including a body that was already merged and sealed.');await pause(3500);
await dialog.getByLabel('Dimension units').selectOption('mm');
await length.fill('4500');await length.blur();
await caption('Type an exact length: 4,500 mm. Width, height and the model update immediately, with proportions locked.');await pause(4500);
await page.screenshot({path:out+'01-live-dimensions.png'});
await dialog.getByRole('button',{name:'+90° Z',exact:true}).click();
await caption('Rotate 90° around Z. The displayed length and width follow the new orientation in real time.');await pause(4000);
await page.screenshot({path:out+'02-rotation.png'});
await dialog.getByRole('button',{name:'Reset changes'}).click();
await length.fill('4500');await length.blur();
await dialog.getByLabel('Rotate Z',{exact:true}).fill('15');
await caption('Fine adjustments also work. Rotating 15° changes the measured bounds; set a target dimension again if needed.');await pause(4500);
await length.fill('4500');await length.blur();
await caption('The live dimensions use actual surface vertices, not an estimate from the old bounding box.');await pause(4000);
await dialog.getByRole('button',{name:'Review changes',exact:true}).click();
await expect(dialog.getByRole('button',{name:'Apply changes',exact:true})).toBeEnabled();
await caption('Review runs geometry checks. Nothing is saved until Apply changes.');await pause(3500);
await dialog.getByRole('button',{name:'Apply changes',exact:true}).click();
await expect(dialog.getByText('Changes applied',{exact:true})).toBeVisible();
await caption('Saved: the new X dimension is 4,500 mm. Original geometry is retained; no CFD simulation was run.');await pause(4500);
await page.screenshot({path:out+'03-applied.png'});
const id=(await readFile(out+'project-id.txt','utf8')).trim();
await writeFile(out+'applied-project.json',JSON.stringify(await(await context.request.get(`http://127.0.0.1:8012/api/projects/${id}`)).json(),null,2));
const video=page.video();await context.close();await video.saveAs(out+'live-dimensions.webm');await browser.close();
await writeFile(out+'browser-errors.json',JSON.stringify(errors));if(errors.length)throw new Error(errors.join('\n'));
console.log(out+'live-dimensions.webm');
