// Record the real import/preview/apply workflow against an isolated local server.
import { chromium, expect } from '../frontend/node_modules/@playwright/test/index.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
const output=new URL('../docs/merge-demo/',import.meta.url).pathname;
const base=process.env.EASYCFD_TEST_URL || 'http://127.0.0.1:8011';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:output,size:{width:1440,height:1000}}});
const p=await(await context.request.post(base+'/api/projects',{data:{sample:true,name:'BMW Z4 · merge demo · 354 components'}})).json();
await writeFile(output+'project-id.txt',p.id);
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const pause=ms=>page.waitForTimeout(ms);
async function click(locator){await locator.scrollIntoViewIfNeeded();const b=await locator.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:15});await pause(250);await locator.click();}
async function caption(text){await page.evaluate(text=>{
  let node=document.getElementById('demo-caption');
  if(!node){node=document.createElement('div');node.id='demo-caption';}
  const parent=document.querySelector('dialog[open]') || document.body;
  parent.appendChild(node);
  node.style.cssText='position:fixed;bottom:36px;right:46px;left:400px;z-index:9999;background:#112a32ed;color:#fff;padding:16px 20px;border-radius:8px;font:16px/1.5 system-ui;pointer-events:none;box-shadow:0 4px 18px #0002';
  node.textContent=text;
},text);}
await page.goto(base);
await expect(page.getByRole('heading',{name:p.name,exact:true})).toBeVisible();
await click(page.getByRole('button',{name:'Import STEP / STL',exact:true}));
await page.getByLabel('Geometry files').setInputFiles(output+'fragmented-z4.stl');
await page.getByLabel('Lowest point above road · m',{exact:true}).fill('0.08');
await caption('Demo fixture: a prepared Z4 body cut into 354 disconnected surface pieces. Wheels are excluded. This is not the original download.');
await pause(5000);
await click(page.getByRole('button',{name:'Import & check model',exact:true}));
await expect(page.getByRole('alert')).toContainText('100 connected');
await caption('1. A normal import fails at the 100-part limit. The existing design is still unchanged.');
await pause(4500);
await page.screenshot({path:output+'01-import-limit.png'});
await page.getByLabel('STL components').selectOption('group');
await caption('2. Choose “Group each STL for repair”. The file can load as one editable part without changing its shape.');
await pause(5000);
await click(page.getByRole('button',{name:'Import & check model',exact:true}));
await expect(page.getByRole('heading',{name:'Import your design'})).toHaveCount(0);
await click(page.getByRole('button',{name:'Merge & seal',exact:true}));
const dialog=page.getByRole('dialog',{name:'Merge and seal'});
await expect(dialog.getByText('354 components',{exact:true})).toBeVisible();
await dialog.getByLabel('Seal resolution').fill('15');
await dialog.getByLabel('Seal gap target').fill('30');
await caption('3. Grouping did not weld the surfaces. Preview a rebuilt body at 15 mm resolution with a 30 mm gap target.');
await pause(5000);
const response=page.waitForResponse(r=>r.url().endsWith('/seal/preview') && r.request().method()==='POST');
await click(dialog.getByRole('button',{name:'Preview merged body',exact:true}));
const preview=await(await response).json();
await writeFile(output+'preview-report.json',JSON.stringify(preview.report,null,2));
await expect(dialog.getByText('354 → 1 solid',{exact:true})).toBeVisible({timeout:30000});
await expect(dialog.getByText('Loading geometry…')).toHaveCount(0);
await caption('4. The preview contains one watertight solid. Surface distances show the changes introduced by reconstruction.');
await pause(5500);
await page.screenshot({path:output+'02-sealed-preview.png'});
await click(dialog.getByRole('button',{name:'Top',exact:true}));
await click(dialog.getByRole('button',{name:'Original',exact:true}));
await caption('5. Compare the original and sealed surfaces from the same camera. Inspect body details, arches, and intentional airflow gaps.');
await pause(4000);
await page.screenshot({path:output+'03-original.png'});
await click(dialog.getByRole('button',{name:'Sealed preview',exact:true}));
await pause(4500);
await page.screenshot({path:output+'04-sealed.png'});
await click(dialog.getByRole('button',{name:'3D',exact:true}));
const canvas=dialog.locator('[data-testid="vtk-viewer"]');const box=await canvas.boundingBox();
await page.mouse.move(box.x+box.width*.6,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6+80,box.y+box.height*.5+30,{steps:30});await page.mouse.up();
await caption('This is approximate reconstruction: existing surface vertices are replaced. The original remains unchanged until Apply.');
await pause(5000);
await click(dialog.getByRole('button',{name:'Apply sealed body',exact:true}));
await expect(dialog.getByText('Sealed body applied',{exact:true})).toBeVisible();
await caption('6. Apply saves the sealed body and reruns geometry checks. Uploaded originals and the prior geometry are preserved.');
await pause(5500);
const download=page.waitForEvent('download');
await click(dialog.getByRole('link',{name:'Download sealed STLs'}));
await(await download).saveAs(output+'sealed-z4-demo.zip');
await caption('The sealed STL is downloaded. This proves the import and repair workflow; no CFD mesh or simulation was run.');
await pause(5000);
await page.screenshot({path:output+'05-applied.png'});
await writeFile(output+'applied-project.json',JSON.stringify(await(await context.request.get(base+`/api/projects/${p.id}`)).json(),null,2));
const video=page.video();await context.close();await video.saveAs(output+'merge-seal-walkthrough.webm');await browser.close();
await writeFile(output+'browser-errors.json',JSON.stringify(errors,null,2));
if(errors.length)throw new Error(errors.join('\n'));
console.log(output+'merge-seal-walkthrough.webm');
