import { expect, test } from "@playwright/test";

test("WebGPU records changing physical frames, plays, seeks and survives reload", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", m => { if (m.type() === "error") errors.push(m.text()); });
  await page.goto("/");
  await page.getByTestId("try-sample").click();
  await page.getByText("I checked size, orientation, wheels and clearance.").click();
  await page.getByRole("button", {name:"Continue to conditions"}).click();
  await page.getByRole("button", {name:"Continue to run"}).click();
  await page.getByText("Expert WebGPU settings", {exact:true}).click();
  await page.getByRole("radio", {name:/Custom/}).click();
  const sliders = page.locator(".step.open input[type=range]");
  await sliders.nth(0).fill("45");
  await sliders.nth(1).fill("2");
  await page.getByRole("switch", {name:"Record flow animation"}).check();
  await expect(page.getByText(/Records 24 frames/)).toBeVisible();
  await page.getByTestId("run").click();
  await expect(page.getByTestId("card-cd")).toBeVisible({timeout:240000});
  const original = await page.evaluate(() => {
    const r = (window as any).__easycfd.app.get().run;
    const a=r.animation, first=a.frames[0], last=a.frames.at(-1);
    let changed=0;
    for(let i=0;i<first.field.u.length;i++) if(!first.field.solid[i] && Math.abs(last.field.u[i]-first.field.u[i])>1e-4) changed++;
    return {result:JSON.stringify(r.doc.result),frames:a.frames.length,times:a.frames.map((f:any)=>f.time),changed,id:r.doc.id};
  });
  expect(original.frames).toBe(24);
  expect(original.times[0]).toBe(0);
  expect(original.times.every((t:number,i:number)=>!i || t>original.times[i-1])).toBe(true);
  expect(original.changed).toBeGreaterThan(100);
  await page.getByRole("button", {name:"Explore airflow"}).click();
  await page.getByTestId("analysis-animation").click();
  await expect(page.getByText("Air speed · transient flow")).toBeVisible();
  await page.getByRole("button", {name:"Pause flow",exact:true}).click();
  const timeline=page.getByRole("slider", {name:"Animation time",exact:true});
  await timeline.fill("0.2");
  const paused = await page.evaluate(()=>(window as any).__easycfd.stages.main.animationPosition());
  expect(paused).toBeCloseTo(.2,2);
  await page.waitForTimeout(300);
  expect(await page.evaluate(()=>(window as any).__easycfd.stages.main.animationPosition())).toBeCloseTo(paused,4);
  await page.getByRole("button", {name:"Play flow",exact:true}).click();
  await page.waitForTimeout(500);
  expect(await page.evaluate(()=>(window as any).__easycfd.stages.main.animationPosition())).toBeGreaterThan(paused);
  await page.getByRole("button", {name:"Pause flow",exact:true}).click();
  await timeline.fill("0.85");
  const before = await page.evaluate(() => ({result:JSON.stringify((window as any).__easycfd.app.get().run.doc.result),gpu:(window as any).__easycfd.stages.main.slice.uniforms.uFrameMix.value}));
  expect(before.result).toBe(original.result);
  expect(before.gpu).toBeGreaterThan(0);
  await page.getByRole("switch", {name:"Loop playback"}).uncheck();
  await timeline.fill("0.98");
  await page.getByRole("button", {name:"Play flow",exact:true}).click();
  await expect(page.getByRole("button", {name:"Play flow",exact:true})).toBeVisible();
  expect(await page.evaluate(()=>(window as any).__easycfd.stages.main.animationPosition())).toBe(1);
  await expect(page.getByTestId("layer-slice")).toHaveAttribute("aria-pressed","false");
  await page.getByTestId("layer-slice").click();
  await expect(page.getByTestId("layer-slice")).toHaveAttribute("aria-pressed","true");
  await expect(page.getByTestId("layer-animation")).toHaveAttribute("aria-pressed","false");
  await page.getByTestId("layer-animation").click();
  await page.screenshot({path:"/tmp/easycfd-animation-review/webgpu-desktop.png"});
  await page.reload();
  await page.evaluate(async id => { const {openRun}=await import("/src/store/runs.ts"); await openRun(id); },original.id);
  expect(await page.evaluate(()=>(window as any).__easycfd.app.get().run.animation.frames.length)).toBe(24);
  await page.setViewportSize({width:390,height:844});
  await page.getByRole("button", {name:"Explore airflow"}).click();
  await page.getByTestId("analysis-animation").click();
  await page.getByRole("button", {name:"View settings"}).click();
  await expect(page.getByRole("slider", {name:"Animation time",exact:true})).toBeVisible();
  await page.screenshot({path:"/tmp/easycfd-animation-review/webgpu-mobile.png"});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
